INSERT INTO demographic_analysis (
    age, 
    occupation, 
    location, 
    zip_code, 
    gender, 
    prediction_location, 
    prediction_location_confidence, 
    prediction_employment, 
    prediction_employment_confidence, 
    prediction_income, 
    prediction_income_confidence, 
    prediction_education, 
    prediction_education_confidence, 
    prediction_health, 
    prediction_health_confidence, 
    prediction_crime, 
    prediction_crime_confidence, 
    prediction_environment, 
    prediction_environment_confidence, 
    prediction_culture, 
    prediction_culture_confidence, 
    prediction_transportation, 
    prediction_transportation_confidence, 
    prediction_housing, 
    prediction_housing_confidence, 
    prediction_technology, 
    prediction_technology_confidence, 
    prediction_social, 
    prediction_social_confidence, 
    prediction_economic, 
    prediction_economic_confidence
) 
VALUES (
    28, 
    'consultant', 
    'Washington DC', 
    '20001', 
    'male', 
    'washington dc or arlington va', 
    'Medium', 
    'senior consultant', 
    'Medium', 
    'Income $125,000-$145,000 in 3 years', 
    'Medium', 
    '60% probability of additional education in 2 years', 
    'Medium', 
    '28% risk of anxiety or burnout in 18 months', 
    'Medium', 
    '22% probability of property crime in 2 years', 
    'Medium', 
    '8-12 days of extreme heat annually by 2026', 
    'Medium', 
    '15-20 cultural events annually, $1,800 on entertainment', 
    'Medium', 
    '65% probability of not owning a car', 
    'Medium', 
    '32-38% of income on housing, 75% probability of renting', 
    'Medium', 
    '2-3 new productivity or AI tools in 12 months', 
    'Medium', 
    '12-15 close connections, 80-120 professional contacts', 
    'Medium', 
    '$35,000-$45,000 in retirement savings in 3 years', 
    'Medium'
);